services:
  admin-mysql_db:
    container_name: admin-mysql_db
    platform: linux/x86_64
    image: mysql:5.7.41
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_PASSWORD: student
    networks:
      - prestashop_network

  prestashop:
    platform: linux/x86_64
    container_name: prestashop
    image: greedann/prestashop
    restart: unless-stopped
    ports:
      - 443:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_196643
      DB_USER: root
      DB_PASSWD: student
      # those parameters ignored by prestashop so must be set manually in app/config/parameters.php

      PS_DOMAIN: localhost
      PS_INSTALL_AUTO: 0
      PS_FOLDER_ADMIN: admin1337
      PS_DEV_MODE: 1
      # set admin email
      ADMIN_MAIL: admin@prestashop.com
      # set admin password
      ADMIN_PASSWD: admin
    networks:
      - prestashop_network
    volumes:
      - ./prestashop_src:/var/www/html
      - ./scripts:/var/www/html/scripts
    # start script to init database
    command: bash -c "chmod +x /var/www/html/scripts/init.sh && sh /var/www/html/scripts/init.sh"

  memcached:
    image: memcached:1.6-alpine
    container_name: BE_196643_memcached
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          cpus: '0.25'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s
    networks:
      - prestashop_network

networks:
  prestashop_network:

