services:
  prestashop:
    image: greedann/prestashop:latest
    ports:
      "19664:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    environment:
      PS_INSTALL_AUTO: 0
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_196643
      DB_USER: root
      DB_PASSWD: student

      PS_ENABLE_SSL: 1
      PS_SSL_ENABLED_EVERYWHERE: 1
      PS_DOMAIN: localhost
      PS_DEV_MODE: 1
    volumes:
      - ./prestashop_src:/var/www/html
      - ./scripts:/var/www/html/scripts
    command: bash -c "chmod +x /var/www/html/scripts/init.sh && sh /var/www/html/scripts/init.sh"

    networks:
      admin-mysql_default
      prestashop_network

  memcached:
    image: memcached:1.6-alpine
    container_name: BE_196643_memcached
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          cpus: '0.25'
          memory: 32M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s
    networks:
      prestashop_network

networks:
  admin-mysql_default:
    external: true

  prestashop_network:
