services:
  admin-mysql_db:
    container_name: admin-mysql_db
    platform: linux/x86_64
    image: mysql:5.7.41
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: student
      MYSQL_DATABASE: BE_196643
      MYSQL_PASSWORD: student
    networks:
      - prestashop_network
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d

  prestashop:
    platform: linux/x86_64
    container_name: prestashop
    image: prestashop-ssl:1
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_196643
      DB_USER: root
      DB_PASSWD: student
      # those parameters ignored by prestashop so must be set manually in app/config/parameters.php

      PS_DOMAIN: localhost
      PS_INSTALL_AUTO: 1
      PS_FOLDER_ADMIN: admin1337
      PS_DEV_MODE: 1
      # set admin email
      ADMIN_MAIL: admin@prestashop.com
      # set admin password
      ADMIN_PASSWD: admin
    networks:
      - prestashop_network
    volumes:
      - ./prestashop_src:/var/www/html

networks:
    prestashop_network:

