<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6qgpkxg\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6qgpkxg/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6qgpkxg.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6qgpkxg\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container6qgpkxg\appDevDebugProjectContainer([
    'container.build_hash' => '6qgpkxg',
    'container.build_id' => '6ad3d3b7',
    'container.build_time' => 1731512186,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6qgpkxg');
