<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF3kv4xa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF3kv4xa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerF3kv4xa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerF3kv4xa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerF3kv4xa\appDevDebugProjectContainer([
    'container.build_hash' => 'F3kv4xa',
    'container.build_id' => '37ddf86a',
    'container.build_time' => 1732624465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF3kv4xa');
