<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvgcqgp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvgcqgp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSvgcqgp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSvgcqgp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSvgcqgp\appProdProjectContainer([
    'container.build_hash' => 'Svgcqgp',
    'container.build_id' => '67ae32b7',
    'container.build_time' => 1729866456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSvgcqgp');
